### ISSUE TITLE
Fail to install rgbif in R 3.1.1

### ISSUE THREAD

**Issue by DupontCai** [ropensci/rgbif#138]
Hi, Scott:

Thanks very much for your working shareing rgbif,This is Dupont, I am having a workshop led by @jhpoelen .  at Texas A&M University Corpus Christi, I am trying to link GBIF to GLOBI, and downloading rgbif; However I found myself fail to install the package, here is the error:

ERROR: dependency ‘rgeos’ is not available for package ‘rgbif’
- removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/rgbif’
  Error: Command failed (1)
  In addition: Warning message:
  package ‘rgeos’ is not available (for R version 3.1.1) 

Thanks,
Dupont
xiaopeng.cai@tamucc.edu

**Comment by s4njr** [comment]
[ First, sorry for my English] Today, I was with same Dupont's problem! In manjaro linux I resolved running "sudo pacman -S geos" in terminal. Maybe, something like this (install geos package) its works in other linux distributions! 

Hugs
Sergio

**Comment by sckott** [comment]
@s4njr Thanks for the feedback here.  As I am not familiar, pacman is only for Arch Linux, correct?

**Comment by s4njr** [comment]
Hi sckott,

Arch and Manjaro linux, because Manjaro is based on Arch Linux. For other distributions people could use as root "apt-get install package's name". For this specific problem I found it: http://grasswiki.osgeo.org/wiki/Compile_and_Install_Ubuntu#GEOS_2.

Take a look on topics 5.2 and 7.2! I don't know if it works, but maybe can useful for someone!

**Comment by s4njr** [comment]
Hi @sckott 

Arch and Manjaro linux, because Manjaro is based on Arch Linux. For other distributions people could use as root "apt-get install package's name". For this specific problem I found it: http://grasswiki.osgeo.org/wiki/Compile_and_Install_Ubuntu#GEOS_2.
Take a look on topics 5.2 and 7.2! I don't know if it works, but maybe can useful for someone!

**Comment by sckott** [comment]
Thanks @s4njr for that information. I'll make a note in the package readme/manual. 

I think I may actually try to remove `rgeos` dependency, since we only use one function I think `readWKT`, which I think we can replace with equally good javascript wrapper version, which should lead to less installation issues #155

**Comment by s4njr** [comment]
It sounds like good solution @sckott. I lost some hours trying to resolve rgeos dependecy. Thanks for attention.

best
Sergio
