### ISSUE TITLE
occ_search bug --> invalid number rows

### ISSUE THREAD

**Issue by 8Ginette8** [ropensci/rgbif#455]
Hi there,

Just wanted to report a bug in occ_search function (and maybe other functions related):

sp.key=c(5325291,5325274)

occ_search(taxonKey=sp.key[1],limit=1)
occ_search(taxonKey=sp.key[1],limit=2)
occ_search(taxonKey=sp.key[1],limit=3)
occ_search(taxonKey=sp.key[1],limit=100)

It seems not to work for certain keys. Not the majority but some species seem to have different number of columns depending on the observational dataset, hence a wrong rbinding when pulling together everything...Seems fast to correct :)

Hope it helps, 
GInette

**Comment by sckott** [comment]
thanks @8Ginette8 

However, I can not replicate your problem. Ideally create a reprex and share session info, see the new issue template https://github.com/ropensci/rgbif/issues/new for info

**Comment by GabrielSlPires** [comment]
Hi there,

Today I had rerun an old script with occ_search() and got the same bug, I think it could happen due to a recent update in GBIF API.
Now I've migrated to occ_data() and everything works nicely here.

This is the function I was using:
```
occ_search(scientificName = as.character(Liu$Species),
                           fields = c('species', 'decimalLatitude', 'decimalLongitude'),
                           hasCoordinate = TRUE,
                           return = 'data')
```
The bug happens without `return = 'data'` also.
And here in this [link](https://advances.sciencemag.org/highwire/filestream/211191/field_highwire_adjunct_files/1/aav1332_Table_S1.xlsx) is the file I've used to generate the Liu data frame.

I hope that could help,
Gabriel

**Comment by sckott** [comment]
Thanks @GabrielSlPires 

Note that in most recent version of rgbif, the `return` parameter in `occ_search` is deprecated - it doesn't do anything anymore - and you should get a warning when its used. 

As above unless you share your R session information, its hard to help
