### ISSUE TITLE
Derived datasets

### ISSUE THREAD

**Issue by dnoesgaard** [ropensci/rgbif#467]
We've recently introduced derived datasets as an easy way of citing non-download data, e.g. data obtained synchronously using occ_search(), etc. I was wondering if we could explore how the citation helper may either employ this service directly (requires authentication) or perhaps help the user prepare a list of datasetKeys with counts?

More here: https://www.gbif.org/citation-guidelines#derivedDatasets

**Comment by jhnwllr** [comment]
It might take some thinking about the best way to point people to the **derived datasets** functionality. 

Since `occ_search` only returns a 100K records, it seems like a `get_derived_dataset()` function from a data.frame with a datasetKey column would be feasible. Might also be nice to have something in the documentation on `occ_search` about derived datasets.

**Comment by jhnwllr** [comment]
This issue is now closed with 

https://github.com/ropensci/rgbif/commit/4a53e5d2799c0982335c2a5c12ab7eea27967b23

You can use `rgbif::derived_dataset()` with the development version of `rgbif`. 

```
pak::pkg_install("ropensci/rgbif")

data <- data.frame(
datasetKey = c(
"3ea36590-9b79-46a8-9300-c9ef0bfed7b8",
"630eb55d-5169-4473-99d6-a93396aeae38",
"806bf7d4-f762-11e1-a439-00145eb45e9a"
),
count = c(3, 1, 2781)
)
  
derived_dataset_prep(
citation_data = data,
title = "Test for derived dataset",
description = "This data was filtered using a fake protocol",
source_url = "https://zenodo.org/record/4246090#.YPGS2OgzZPY",
)
```
