### ISSUE TITLE
usageKey, taxonKey, speciesKey

### ISSUE THREAD

**Issue by CharlottePhilps** [ropensci/rgbif#476]
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BIEN_1.2.4        RPostgreSQL_0.6-2 DBI_1.1.1         bit64_4.0.5       bit_4.0.4        
 [6] countrycode_1.3.0 stringr_1.4.0     data.table_1.14.0 dplyr_1.0.7       plyr_1.8.6       
[11] rgbif_3.6.0    

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>
Hi there, 

Not so much an issue with script or the packages themselves. 

But I was wondering what the difference is between usageKey, taxonKey and speciesKey?

When getting the backbone ID's of species it returns usageKey and speciesKey. 
However once importing an occ_download there is only speciesKey or taxonKey- when I try to link back to check taxonKeys are in the usageKeys I used to obtain my downloads, I find that some are not. 

Im downloading a few hundred species but as an example, "Rhinotropis nitida" the usageKey does not appear in a taxonKey (I think because of subspecies/ varieties) but does in the speciesKey. 

I would download with script something like this: 

  res <- name_backbone("Rhinotropis nitida")
  taxonkey <- as.numeric(res$usageKey)
  
w <- occ_download(pred_in("taxonKey", taxonkey),pred("hasCoordinate", TRUE),
                  pred("hasGeospatialIssue", FALSE),
                  format="SIMPLE_CSV",
                  user=usr,
                  pwd=pwd,
                  email=myemail)

I think the species names in the occ_download may return the accepted name for the species according to the GBIF backbone instead of the name I'm searching for (as when checking my downloaded names for other species they dont always appear in my download $species column) so would like to be able to attach my synonym to the records to investigate further and was going to do this by usageKey (but this doesn't seem to be in the download).

Is there a way to do this? Am I looking at the wrong columns or downloading the wrong information? 

Thanks,
Charlotte

**Comment by jhnwllr** [comment]
@CharlottePhilps 
Thanks for the question.  

> But I was wondering what the difference is between usageKey, taxonKey and speciesKey?

Often **usageKey**, **taxonKey** and **speciesKey** will be they same thing. When running `rgbif::name_backbone`, usageKey == taxonKey **will always be the same**.  usageKey is some special terminology that gets used when dealing with checklists, but it is equivalent to the GBIF taxonKey in the context of the GBIF backbone. 

If your name matched to something higher than rank species, then your speciesKey **will not exist** because your name is not of rank species in the GBIF backbone. Any synonym name will also get its own taxonKey/usageKey (**if it matches to the species rank or lower**).  

For the case of "Rhinotropis nitida", it only matches to the GBIF backbone at rank GENUS, so the name is not present in the GBIF backbone only genus "Rhinotropis". 

>I think the species names in the occ_download may return the accepted name for the species according to the GBIF backbone

For type `format="SIMPLE_CSV"` (the default), you will only get back the "interpreted" names that have matched to the GBIF backbone. If you cho0se `format="DWCA"`, then you will get back a much larger file with the original names supplied by the publisher. The download will still download everything thing in the higherrank that got matched (i.e. the "Rhinotropis" genus), so you might be able to find things like "Rhinotropis nitida" in the larger DWCA download within **verbatim.txt**.

**Comment by jhnwllr** [comment]
https://discourse.gbif.org/t/understanding-gbif-taxonomic-keys-usagekey-taxonkey-specieskey/3045
