### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by visamilar** [ropensci/rgbif#543]
Trying to run the example command #for single species on R4.2.1 with x86_64, darwin17.0 to download data, the error message is 

Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  SSL certificate problem: certificate has expired

If it is on Windows I could turn off the security for a moment, how could I do it on IOS? Do you have any suggestion? Thanks a lot.

<details> <summary><strong>Session Info</strong></summary>

Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  SSL certificate problem: certificate has expired

</details>

**Comment by MattBlissett** [comment]
Hi,

The SSL certificates for gbif.org are valid, and it shouldn't be necessary to disable certificate checking — see https://api.gbif.org/, for example.

You probably have an old version of Curl or other OS security updates which should be applied.

(Does Darwin17.0 mean Mac OS 10.13 High Sierra? That has not been supported by Apple since November 2020.)
