### ISSUE TITLE
add missing occ_search terms

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#698]
https://techdocs.gbif.org/en/openapi/v1/occurrence#/Searching%20occurrences/searchOccurrence

**Comment by jhnwllr** [comment]
- [ ] startDayOfYear
- [ ] endDayOfYear
- [ ] parentEventId
- [ ] samplingProtocol
- [ ] previousIdentifications
- [ ] modified
- [ ] gbifRegion
- [ ] publishedByGbifRegion
- [ ] sex
- [ ] isSequenced
- [ ] acceptedTaxonKey
- [ ] taxonId
- [ ] taxonConceptId
- [ ] taxonomicStatus
- [ ] geoDistance
- [ ] pathway
- [ ] installationKey
- [ ] hostingOrganizationKey
- [ ] crawlId
- [ ] projectId
- [ ] programme
- [ ] sampleSizeUnit
- [ ] sampleSizeValue
- [ ] collectionKey
- [ ] institutionKey
- [ ] recordedById
- [ ] identifiedById
- [ ] gadmLevel0Gid
- [ ] gadmLevel1Gid
- [ ] gadmLevel2Gid
- [ ] gadmLevel3Gid
- [ ] dwcaExtension
- [ ] datasetId
- [ ] datasetName
- [ ] otherCatalogNumbers
- [ ] preparations
- [ ] island
- [ ] islandGroup
- [ ] georeferencedBy
- [ ] higherGeography
- [ ] fieldNumber
- [ ] earliestEonOrLowestEonothem
- [ ] latestEonOrHighestEonothem
- [ ] earliestEraOrLowestErathem
- [ ] latestEraOrHighestErathem
- [ ] earliestPeriodOrLowestSystem
- [ ] latestPeriodOrHighestSystem
- [ ] earliestEpochOrLowestSeries
- [ ] latestEpochOrHighestSeries
- [ ] earliestAgeOrLowestStage
- [ ] latestAgeOrHighestStage
- [ ] lowestBiostratigraphicZone
- [ ] highestBiostratigraphicZone
- [ ] group
- [ ] formation
- [ ] member
- [ ] bed
- [ ] associatedSequences
- [ ] gbifId

**Comment by veronicar239** [comment]
I've been using institutionKey in occ_count() queries and would like to use institutionKey for occ_download(). I am specifically using institutionKey because it is the [highest level identifier of an institution (may include multiple institutionCode for a given institution)](https://github.com/gbif/portal-feedback/issues/5873). The institutionKey is the primary GBIF identifier. 

However, I am getting errors related to trying to use institutionKey with occ_download():

> occ_download_prep("institutionKey", "586ee56e-b0fe-4dff-b7f9-aeb104f3308a")
Error: all inputs must be class occ_predicate/occ_predicate_list; ?occ_download

> occ_download_prep(pred_or(pred("institutionKey", "586ee56e-b0fe-4dff-b7f9-aeb104f3308a"), pred("institutionKey", "be5b9c72-e499-42b8-a5dc-c27505cf232e"), pred("institutionKey", '6a6ac6c5-1b8a-48db-91a2-f8661274ff80'), pred("institutionKey", '0e919a55-08d3-4bd2-aec1-200858fafd92')))
Error: 'institutionKey' not in acceptable set of keys; see ?download_predicate_dsl

Could you please advise how to use institutionKey with occ_download?
